<?php
/**
 * @file
 * Sample data for Able Organizer install profile.
 */

/**
 * Sample data for CRM Core Donation Demo install profile.
 */
function ableorganizer_sample_data() {
  $sample_data = array (
    'crm_core_contact' =>
    array (
      2 => '{
  "vid" : "16",
  "log" : "",
  "created" : "1377557220",
  "changed" : "1378480551",
  "uid" : "1",
  "contact_id" : "2",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Thomas",
        "middle" : "Ruggles",
        "family" : "Pynchon",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Thomas",
          "middle" : "Ruggles",
          "family" : "Pynchon",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1962-08-14 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "pynchont@yoyodyne.com" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "CT",
        "sub_administrative_area" : null,
        "locality" : "Cudworth",
        "dependent_locality" : null,
        "postal_code" : "06818-8100",
        "thoroughfare" : "5972 Quiet Blossom Circuit",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "2037029917", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      3 => '{
  "vid" : "21",
  "log" : "",
  "created" : "1377557222",
  "changed" : "1378481066",
  "uid" : "1",
  "contact_id" : "3",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Jonathan",
        "middle" : "Simmons",
        "family" : "Barth",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Jonathan",
          "middle" : "Simmons",
          "family" : "Barth",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1995-09-06 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "john.barth@fiveseasons.com" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "IN",
        "sub_administrative_area" : null,
        "locality" : "Antler",
        "dependent_locality" : null,
        "postal_code" : "46808-4556",
        "thoroughfare" : "6488 Red Place",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "7654802886", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      4 => '{
  "vid" : "15",
  "log" : "",
  "created" : "1377557224",
  "changed" : "1378480441",
  "uid" : "1",
  "contact_id" : "4",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "David",
        "middle" : "Foster",
        "family" : "Wallace",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "David",
          "middle" : "Foster",
          "family" : "Wallace",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1982-10-13 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "david.wallace5@peoria.irs.gov" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "OR",
        "sub_administrative_area" : null,
        "locality" : "Curfew",
        "dependent_locality" : null,
        "postal_code" : "97423-6608",
        "thoroughfare" : "2619 Quaking Leaf Farms",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "9719273347", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      5 => '{
  "vid" : "20",
  "log" : "",
  "created" : "1377557227",
  "changed" : "1378480936",
  "uid" : "1",
  "contact_id" : "5",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Hansel",
        "middle" : "Friedrich",
        "family" : "Fallada",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Hansel",
          "middle" : "Friedrich",
          "family" : "Fallada",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1978-12-22 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "falladah@dp-dhl.com" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "CT",
        "sub_administrative_area" : null,
        "locality" : "Marquis",
        "dependent_locality" : null,
        "postal_code" : "06945-7254",
        "thoroughfare" : "3289 Heather Beacon Pathway",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "4751547833", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      6 => '{
  "vid" : "14",
  "log" : "",
  "created" : "1377557229",
  "changed" : "1378480314",
  "uid" : "1",
  "contact_id" : "6",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Roland",
        "middle" : "Gerard",
        "family" : "Barthes",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Roland",
          "middle" : "Gerard",
          "family" : "Barthes",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1990-02-21 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "rgb@mythologies.fr" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "TX",
        "sub_administrative_area" : null,
        "locality" : "Oldrag",
        "dependent_locality" : null,
        "postal_code" : "78028-2555",
        "thoroughfare" : "634 Hazy Robin Pike",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "9033973316", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      7 => '{
  "vid" : "19",
  "log" : "",
  "created" : "1377557231",
  "changed" : "1378480839",
  "uid" : "1",
  "contact_id" : "7",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Tom",
        "middle" : "Coraghessan",
        "family" : "Boyle",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Tom",
          "middle" : "Coraghessan",
          "family" : "Boyle",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1984-11-07 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "tcboyle@usc.edu" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "OR",
        "sub_administrative_area" : null,
        "locality" : "Tip Top",
        "dependent_locality" : null,
        "postal_code" : "97822-9789",
        "thoroughfare" : "9170 Merry Creek Way",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "4584319059", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      8 => '{
  "vid" : "13",
  "log" : "",
  "created" : "1377557233",
  "changed" : "1378480183",
  "uid" : "1",
  "contact_id" : "8",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Stephen",
        "middle" : "Michael",
        "family" : "Erickson",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Stephen",
          "middle" : "Michael",
          "family" : "Erickson",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1989-06-13 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "bigfan@allmovies.com" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "IN",
        "sub_administrative_area" : null,
        "locality" : "Third Cliff",
        "dependent_locality" : null,
        "postal_code" : "47587-6597",
        "thoroughfare" : "4242 Rustic Rabbit Canyon",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "3171391106", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      9 => '{
  "vid" : "18",
  "log" : "",
  "created" : "1377557235",
  "changed" : "1378480747",
  "uid" : "1",
  "contact_id" : "9",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Bill",
        "middle" : "Ford",
        "family" : "Gibson",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Bill",
          "middle" : "Ford",
          "family" : "Gibson",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1987-08-29 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "gibsonb@wintermute.it" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "WV",
        "sub_administrative_area" : null,
        "locality" : "Black Hog Landing",
        "dependent_locality" : null,
        "postal_code" : "26185-3141",
        "thoroughfare" : "2487 Pleasant Apple Ramp",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "3042488587", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      10 => '{
  "vid" : "12",
  "log" : "",
  "created" : "1377557237",
  "changed" : "1378479916",
  "uid" : "1",
  "contact_id" : "10",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "Marcus",
        "middle" : "Zachary",
        "family" : "Danielewski",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "Marcus",
          "middle" : "Zachary",
          "family" : "Danielewski",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1987-03-11 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "mzd@50year.com" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "IN",
        "sub_administrative_area" : null,
        "locality" : "Yarbo",
        "dependent_locality" : null,
        "postal_code" : "47869-8009",
        "thoroughfare" : "5986 Amber Island Bank",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "7651989087", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
      11 => '{
  "vid" : "17",
  "log" : "",
  "created" : "1377557240",
  "changed" : "1378480632",
  "uid" : "1",
  "contact_id" : "11",
  "type" : "individual",
  "default_revision" : "1",
  "contact_name" : { "und" : [
      {
        "title" : "",
        "given" : "William",
        "middle" : "Thomas",
        "family" : "Gaddis",
        "generational" : "",
        "credentials" : "",
        "safe" : {
          "title" : "",
          "given" : "William",
          "middle" : "Thomas",
          "family" : "Gaddis",
          "generational" : "",
          "credentials" : ""
        }
      }
    ]
  },
  "field_ao_birthday" : { "und" : [
      {
        "value" : "1994-06-14 00:00:00",
        "timezone" : "UTC",
        "timezone_db" : "UTC",
        "date_type" : "datetime"
      }
    ]
  },
  "field_ao_business_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "",
        "sub_administrative_area" : null,
        "locality" : "",
        "dependent_locality" : null,
        "postal_code" : "",
        "thoroughfare" : "",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_email_address" : { "und" : [ { "email" : "gaddis.william@carpenters.org" } ] },
  "field_ao_facebook" : [],
  "field_ao_home_address" : { "und" : [
      {
        "country" : "US",
        "administrative_area" : "NE",
        "sub_administrative_area" : null,
        "locality" : "Merry Midnight",
        "dependent_locality" : null,
        "postal_code" : "68257-1715",
        "thoroughfare" : "587 Shady Wagon Lookout",
        "premise" : "",
        "sub_premise" : null,
        "organisation_name" : null,
        "name_line" : null,
        "first_name" : null,
        "last_name" : null,
        "data" : null
      }
    ]
  },
  "field_ao_primary_telephone" : { "und" : [ { "number" : "3082228223", "country_codes" : "us", "extension" : "" } ] },
  "field_ao_twitter" : [],
  "rdf_mapping" : []
}',
    ),
    'crm_core_activity' =>
    array (),
  );

  return $sample_data;
}
