<?php
/**
 * @file
 * Code for the AbleOrganizer Sample Donation Pages feature.
 */

include_once 'ableorganizer_sample_donation_pages.features.inc';

/**
 * Helper to rebuild uuid_node feature component..
 */
function _ableorganizer_sample_donation_pages_rebuild_nodes() {
  // Saving profile nodes configuration.
  $module = 'ableorganizer_sample_donation_pages';
  // Including sample nodes definitions.
  module_load_include('inc', $module, $module . '.features.uuid_node');
  // Including helper.
  module_load_include('inc', 'uuid_features', 'includes/uuid_node.features');
  // Creating sample content in DB.
  uuid_node_features_rebuild($module);
}
