<?php
/**
 * @file
 * Code for the Able Organizer Donation Sample Content feature.
 */

include_once 'ableorganizer_donation_sample_content.features.inc';

/**
 * Implements hook_enable().
 */
function ableorganizer_donation_sample_content_enable() {
  _ableorganizer_donation_sample_content_set_config();
}

/**
 * Helper to set config for donation content.
 */
function _ableorganizer_donation_sample_content_set_config() {
  module_enable(array('uuid', 'uuid_path', 'uuid_features'));
  // Saving profile nodes configuration.
  $module = 'ableorganizer_donation_sample_content';

  // Including sample nodes definitions.
  module_load_include('inc', $module, $module . '.features.uuid_node');

  // Including helper.
  module_load_include('inc', 'uuid_features', 'includes/uuid_node.features');

  // Creating sample content in DB.
  uuid_node_features_rebuild($module);
  $content_uuids = array(
    'online_donation' => 'e5742cc9-af29-4b1a-930b-24921ae633d4',
    'annual_appeal' => '3e876d31-271a-47da-8564-2bb667953ade',
    'fundraiser' => '2b66066f-0a98-43b7-bc0e-a74c6e4130e6',
    'donate' => 'c0bbb31c-980f-4732-ac60-c0931c74448e',
  );

  // Getting local IDs from universal.
  $nids = entity_get_id_by_uuid('node', $content_uuids);

  // Set the appropriate profile forms for the donation pages.
  $crm_core_profile_nodes = array(
    array(
      'nid' => $nids[$content_uuids['online_donation']],
      'use_profile' => '1',
      'profile_name' => 'ao_donation_form',
      'display_profile' => '1',
      'inline_title' => 'Donation form',
    ),
    array(
      'nid' => $nids[$content_uuids['annual_appeal']],
      'use_profile' => '1',
      'profile_name' => 'ao_annual_appeal_form',
      'display_profile' => '1',
      'inline_title' => 'Annual appeal form',
    ),
    array(
      'nid' => $nids[$content_uuids['fundraiser']],
      'use_profile' => '1',
      'profile_name' => 'ao_fundraiser_form',
      'display_profile' => '1',
      'inline_title' => 'Fundraiser form',
    ),
  );
  $fields = array(
    'nid',
    'use_profile',
    'profile_name',
    'display_profile',
    'inline_title',
  );
  $query = db_insert('crm_core_profile_nodes')
    ->fields($fields);

  foreach ($crm_core_profile_nodes as $node_config) {
    $query->values($node_config);
  }

  $query->execute();

  // Configure the default email settings, if they are enabled.
  $thank_you_email = '';
  if (variable_get('configure_donation_email', 0) === 1) {
    $thank_you_email = 'rules_cmcd_thank_you_message';
  }

  // Create the appropriate settings for each donation page.
  $donation_page_settings = array(
    array(
      'nid' => $nids[$content_uuids['online_donation']],
      'recommended_amounts' => '',
    ),
    array(
      'nid' => $nids[$content_uuids['annual_appeal']],
      'recommended_amounts' => '250',
    ),
    array(
      'nid' => $nids[$content_uuids['fundraiser']],
      'recommended_amounts' => '10,25,50,100,250,500,1000,5000',
    ),
  );

  $query = db_insert('crm_core_donation_nodes')
    ->fields(array('nid', 'thanks_email', 'recommended_amounts'));
  foreach ($donation_page_settings as $item) {
    $query->values(
      array(
        $item['nid'],
        $thank_you_email,
        $item['recommended_amounts'],
      )
    );
  }
  $query->execute();

  // Saving path alias for 'Thank you' page.
  $thank_you_uuid = '7c28ea35-4da6-4316-91ca-6e5ca19f79f1';
  $thank_you_id = entity_get_id_by_uuid('node', array($thank_you_uuid));
  $thank_you_id = $thank_you_id[$thank_you_uuid];

  // Setup aliases.
  $content_aliases = array();
  $content_aliases[] = array(
    'source' => 'node/' . $thank_you_id,
    'alias' => 'donate/thank-you',
  );
  $content_aliases[] = array (
    'source' => 'node/' . $nids[$content_uuids['online_donation']],
    'alias' => 'donate/online-donation',
  );
  $content_aliases[] = array(
    'source' => 'node/' . $nids[$content_uuids['annual_appeal']],
    'alias' => 'donate/annual-appeal',
  );
  $content_aliases[] = array(
    'source' => 'node/' . $nids[$content_uuids['fundraiser']],
    'alias' => 'donate/fundraiser',
  );
  $content_aliases[] = array(
    'source' => 'node/' . $nids[$content_uuids['donate']],
    'alias' => 'donate',
  );
  foreach($content_aliases as $path) {
    path_save($path);
  }
}
